site_name: AnyContent
pages:
- [index.md, Home]
- [about.md, Overview, About]
- [cmdl.md, Content Definition, CMDL]
- [cmdl/text.md, Content Definition, Text Input]
- [cmdl/numerical.md, Content Definition, Numerical Input]
- [cmdl/selections.md, Content Definition, Selections]
- [cmdl/files-and-images.md, Content Definition, Files & Images]
- [cmdl/data-structures.md, Content Definition, Data Structures]
- [cmdl/source-code-input.md, Content Definition, Source Code Input]
- [cmdl/form-composition.md, Content Definition, Form Composition]
- [cmdl/others.md, Content Definition, Other Form Elements]
- [cmdl/annotations.md, Content Definition, Annotations]
- [cmdl/views.md, Content Definition, Views]
- [cmdl/clippings.md, Content Definition, Clippings]
- [api/api.md, Content Access, API]
- [anycontent/index.md, Content Editing]
theme: readthedocs